version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk  # Utilizamos una imagen Docker con OpenJDK 11 preinstalado

    working_directory: ~/repo

    steps:
      - checkout

      # Configuramos el entorno Java
      - run:
          name: Setup Java
          command: |
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            java -version
            javac -version

      # Compilamos el proyecto
      - run:
          name: Build
          command: mvn clean install

      # Ejecutamos las pruebas
      - run:
          name: Run Tests
          command: mvn test

# Configuramos el flujo de trabajo para ejecutar el job 'build' en cada push al repositorio
workflows:
  version: 2
  build:
    jobs:
      - build
